##var = 10/0
##print(var)
##print("welcome")

# Exception ---> zeroDivisionError, IndexError, ArithmeticError

##try:
##    var = 10/0
##    print(var)
##
##except:
##    print("sorry")
##
##print("welcome")

##var = "a" + 10
##print(var)

##try:
##    var = "a" + 10
##    print(var)
##
##except:  #Default exception block
##    print("sorry")
##
##print("welcome")
    
##try:
##    var = "a" + 10
##    print(var)
##    
##except TypeError:
##    print("sorry try again")
##    
##except:  #Default exception block
##    print("sorry")
##
##print("welcome")

##try:
##    var = 10/0
##    print(var)
##    
##except TypeError:
##    print("sorry try again")
##    
##except:  #Default exception block
##    print("sorry")
##
##print("welcome")

##try:
##    var = 10/0
##    print(var)
##    
##except TypeError:
##    print("sorry try again")
##    
##except ZeroDivisionError:
##    print("sorry for the error")
##
##except:
##    print("sorry")

##try:
##    var = "ag" + 5
##    print(var)
##    
##except TypeError as exi:
##    print(exi)
##    
##except ZeroDivisionError as hello:
##    print(hello)
##
##except:                   #default exception block an it should be always last
##    print("sorry")

##try:
##    var = 10/0
##    print(var)
##    
##except (TypeError,ZeroDivisionError) as exi:
##    print(exi)
##
##except:
##    print(sorry)

##try:
##    var = 10/0
##    print(var)
##
##except Exception as ex:
##    print(ex)
    
##try:
##    var = 10/4
##    print(var)
##
##except Exception as ex:
##    print(ex)
##
##else:
##    print("my else book")
##    
##finally:
##    ("my block of finally")

##var = 10
##try:
##    if var>5:
##        raise IndexError()
##
##except IndexError:
##    print("sorry")

##var = 10
##try:
##    if var>5:
##        raise IndexError()
##
##except IndexError as ex:
##    print(ex)

##var = 10
##try:
##    if var>5:
##        raise IndexError("my raising of error")
##
##except IndexError as ex:
##    print(ex)

##class Netzwer_academy(Exception):
##    pass
##var = 10
##try:
##    if var>5:
##        raise Netzwer_academy("my raising of error")
##
##except Netzwer_academy as ex:
##    print(ex)

##class Netzwer_academy(Exception):
##    pass
##var = 10
##try:
##    if var>5:
##        raise Netzwer_academy("my raising of error")
##
##except Netzwer_academy as ex:
##    print(ex)

##class Netzwer_academy(Exception):
##    pass
##var = 10
##try:
##    if var>5:
##        raise Netzwer_academy()
##
##except Netzwer_academy:
##    print("sorry")

##class Netzwer_academy(Exception):
##    my_error = "user defined exception"
##var = 10
##try:
##    if var>5:
##        raise Netzwer_academy()
##
##except Netzwer_academy:
##    print("sorry")

##class Netzwer_academy(Exception):
##    my_error = "user defined exception"
##var = 10
##try:
##    if var>5:
##        raise Netzwer_academy()
##
##except Netzwer_academy as ex:
##    print(ex.my_error)

##class Netzwer_academy(Exception):
##    kuch
##var = 10
##try:
##    if var>5:
##        raise Netzwer_academy()
##
##except Netzwer_academy:
##    print("sorry")
